//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizatorStudija
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseStaff
    {
        public int table_staff_id { get; set; }
        public int table_course_id { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual course course { get; set; }
    }
}
