//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizatorStudija
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public course()
        {
            this.userCourses = new HashSet<userCourses>();
            this.courseStaffs = new HashSet<courseStaff>();
        }
    
        public int course_id { get; set; }
        public string name { get; set; }
        public short ects { get; set; }
        public short year { get; set; }
        public string colour { get; set; }
    
        public virtual ICollection<userCourses> userCourses { get; set; }
        public virtual ICollection<courseStaff> courseStaffs { get; set; }
    }
}
