//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizatorStudija
{
    using System;
    using System.Collections.Generic;
    
    public partial class usefull_link
    {
        public int link_id { get; set; }
        public string link { get; set; }
        public int table_user_id { get; set; }
        public string name { get; set; }
    
        public virtual user user { get; set; }
    }
}
